package entity;
// Generated Aug 18, 2023 1:16:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employers generated by hbm2java
 */
@Entity
@Table(name="Employers"
    ,schema="dbo"
    ,catalog="tests"
)
public class Employers {


     private int id;
     private int userId;
     private Date dateCreated;
     private Date dateUpdated;
     private int createdBy;
     private Integer updatedBy;

    public Employers() {
    }

	
    public Employers(int id, int userId, Date dateCreated, int createdBy) {
        this.id = id;
        this.userId = userId;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public Employers(int id, int userId, Date dateCreated, Date dateUpdated, int createdBy, Integer updatedBy) {
       this.id = id;
       this.userId = userId;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateCreated", nullable=false, length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=23)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    
    @Column(name="CreatedBy", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UpdatedBy")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


