package entity;
// Generated Aug 18, 2023 1:16:26 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name="Jobs"
    ,schema="dbo"
    ,catalog="tests"
)
public class Jobs {


     private int id;
     private String title;
     private String description;
     private String locationText;
     private String requirements;
     private BigDecimal salary;
     private String tags;
     private Date dateCreated;
     private Date dateUpdated;
     private int createdBy;
     private Integer updatedBy;

    public Jobs() {
    }

	
    public Jobs(int id, String title, String description, String locationText, String requirements, BigDecimal salary, Date dateCreated, int createdBy) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.locationText = locationText;
        this.requirements = requirements;
        this.salary = salary;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public Jobs(int id, String title, String description, String locationText, String requirements, BigDecimal salary, String tags, Date dateCreated, Date dateUpdated, int createdBy, Integer updatedBy) {
       this.id = id;
       this.title = title;
       this.description = description;
       this.locationText = locationText;
       this.requirements = requirements;
       this.salary = salary;
       this.tags = tags;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="locationText", nullable=false)
    public String getLocationText() {
        return this.locationText;
    }
    
    public void setLocationText(String locationText) {
        this.locationText = locationText;
    }

    
    @Column(name="Requirements", nullable=false)
    public String getRequirements() {
        return this.requirements;
    }
    
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }

    
    @Column(name="Salary", nullable=false, precision=10)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    
    @Column(name="Tags")
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateCreated", nullable=false, length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=23)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    
    @Column(name="CreatedBy", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UpdatedBy")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


