package entity;
// Generated Aug 14, 2023 6:40:26 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Persons generated by hbm2java
 */
public class Persons {

    private int id;
    private int userId;
    private Integer balanceId;
    private String identification;
    private String firstName;
    private String lastName;
    private String primaryPhoneNumber;
    private String secondaryPhoneNumber;
    private Date dateCreated;
    private Date dateUpdated;
    private int createdBy;
    private Integer updatedBy;

    public Persons() {
    }

    public Persons(int id, int userId, Date dateCreated, int createdBy) {
        this.id = id;
        this.userId = userId;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }

    public Persons(int id, int userId, Integer balanceId, String identification, String firstName, String lastName, String primaryPhoneNumber, String secondaryPhoneNumber, Date dateCreated, Date dateUpdated, int createdBy, Integer updatedBy) {
        this.id = id;
        this.userId = userId;
        this.balanceId = balanceId;
        this.identification = identification;
        this.firstName = firstName;
        this.lastName = lastName;
        this.primaryPhoneNumber = primaryPhoneNumber;
        this.secondaryPhoneNumber = secondaryPhoneNumber;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Integer getBalanceId() {
        return this.balanceId;
    }

    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }

    public String getIdentification() {
        return this.identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }

    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }

    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }

    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

}
