package entity;
// Generated Aug 18, 2023 1:16:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Persons generated by hbm2java
 */
@Entity
@Table(name="Persons"
    ,schema="dbo"
    ,catalog="tests"
    , uniqueConstraints = @UniqueConstraint(columnNames="Identification") 
)
public class Persons {


     private int id;
     private int userId;
     private Integer balanceId;
     private String identification;
     private String firstName;
     private String lastName;
     private String primaryPhoneNumber;
     private String secondaryPhoneNumber;
     private Date dateCreated;
     private Date dateUpdated;
     private int createdBy;
     private Integer updatedBy;

    public Persons() {
    }

	
    public Persons(int id, int userId, String identification, Date dateCreated, int createdBy) {
        this.id = id;
        this.userId = userId;
        this.identification = identification;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public Persons(int id, int userId, Integer balanceId, String identification, String firstName, String lastName, String primaryPhoneNumber, String secondaryPhoneNumber, Date dateCreated, Date dateUpdated, int createdBy, Integer updatedBy) {
       this.id = id;
       this.userId = userId;
       this.balanceId = balanceId;
       this.identification = identification;
       this.firstName = firstName;
       this.lastName = lastName;
       this.primaryPhoneNumber = primaryPhoneNumber;
       this.secondaryPhoneNumber = secondaryPhoneNumber;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="BalanceId")
    public Integer getBalanceId() {
        return this.balanceId;
    }
    
    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }

    
    @Column(name="Identification", unique=true)
    public String getIdentification() {
        return this.identification;
    }
    
    public void setIdentification(String identification) {
        this.identification = identification;
    }

    
    @Column(name="FirstName")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LastName")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="PrimaryPhoneNumber")
    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }
    
    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }

    
    @Column(name="SecondaryPhoneNumber")
    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }
    
    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateCreated", nullable=false, length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DateUpdated", length=23)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    
    @Column(name="CreatedBy", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UpdatedBy")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


