package entity;
// Generated Aug 14, 2023 6:40:26 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users {

    private int id;
    private int profileId;
    private Integer userImageId;
    private String username;
    private String primaryEmail;
    private String secondaryEmail;
    private String password;
    private String tempPassword;
    private int statusId;
    private Date lastLogin;
    private Date dateCreated;
    private Date dateUpdated;
    private int createdBy;
    private Integer updatedBy;

    public Users() {
    }

    public Users(int id, int profileId, String username, String primaryEmail, String password, int statusId, Date dateCreated, int createdBy) {
        this.id = id;
        this.profileId = profileId;
        this.username = username;
        this.primaryEmail = primaryEmail;
        this.password = password;
        this.statusId = statusId;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }

    public Users(int id, int profileId, Integer userImageId, String username, String primaryEmail, String secondaryEmail, String password, String tempPassword, int statusId, Date lastLogin, Date dateCreated, Date dateUpdated, int createdBy, Integer updatedBy) {
        this.id = id;
        this.profileId = profileId;
        this.userImageId = userImageId;
        this.username = username;
        this.primaryEmail = primaryEmail;
        this.secondaryEmail = secondaryEmail;
        this.password = password;
        this.tempPassword = tempPassword;
        this.statusId = statusId;
        this.lastLogin = lastLogin;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getProfileId() {
        return this.profileId;
    }

    public void setProfileId(int profileId) {
        this.profileId = profileId;
    }

    public Integer getUserImageId() {
        return this.userImageId;
    }

    public void setUserImageId(Integer userImageId) {
        this.userImageId = userImageId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPrimaryEmail() {
        return this.primaryEmail;
    }

    public void setPrimaryEmail(String primaryEmail) {
        this.primaryEmail = primaryEmail;
    }

    public String getSecondaryEmail() {
        return this.secondaryEmail;
    }

    public void setSecondaryEmail(String secondaryEmail) {
        this.secondaryEmail = secondaryEmail;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTempPassword() {
        return this.tempPassword;
    }

    public void setTempPassword(String tempPassword) {
        this.tempPassword = tempPassword;
    }

    public int getStatusId() {
        return this.statusId;
    }

    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    public Date getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

}
